class BreedRisk {
  final int heatRisk;        // 暑さリスク 1-5
  final int coldRisk;        // 寒さリスク 1-5
  final int humidityRisk;    // 湿度リスク 1-5
  final int respiratoryRisk; // 呼吸器リスク 1-5
  final int skinRisk;        // 皮膚リスク 1-5
  final int jointRisk;       // 関節リスク 1-5
  final int earRisk;         // 耳リスク 1-5
  final int eyeRisk;         // 目リスク 1-5
  final int stomachRisk;     // 胃リスク 1-5
  final bool shortNose;      // 短頭種
  final bool longBack;       // 胴長
  final bool giantBreed;     // 超大型

  const BreedRisk({
    this.heatRisk = 3,
    this.coldRisk = 3,
    this.humidityRisk = 3,
    this.respiratoryRisk = 3,
    this.skinRisk = 3,
    this.jointRisk = 3,
    this.earRisk = 3,
    this.eyeRisk = 3,
    this.stomachRisk = 2,
    this.shortNose = false,
    this.longBack = false,
    this.giantBreed = false,
  });
}

class Breed {
  final String id;
  final String jaName;
  final String kana;
  final String enName;
  final List<String> aliases;
  final String jkcGroup;
  final String akcGroup;
  final String sizeDefault; // SS/S/M/L/XL
  final String coatLength;  // 短毛/中毛/長毛
  final String coatType;    // シングル/ダブル/巻き毛/ワイヤー
  final String exerciseLevel; // low/medium/high/very_high
  final BreedRisk risk;
  final String notesJa;

  const Breed({
    required this.id,
    required this.jaName,
    required this.kana,
    required this.enName,
    this.aliases = const [],
    this.jkcGroup = '',
    this.akcGroup = '',
    required this.sizeDefault,
    required this.coatLength,
    required this.coatType,
    this.exerciseLevel = 'medium',
    required this.risk,
    this.notesJa = '',
  });
}

// =============================
// JKC 1G：牧羊犬・牧畜犬
// =============================
const List<Breed> jkc1gBreeds = [
  Breed(
    id: 'border_collie',
    jaName: 'ボーダー・コリー',
    kana: 'ぼーだーこりー',
    enName: 'Border Collie',
    aliases: ['ボーダーコリー', 'BC'],
    jkcGroup: '1G',
    akcGroup: 'Herding',
    sizeDefault: 'M',
    coatLength: '中毛',
    coatType: 'ダブル',
    exerciseLevel: 'very_high',
    risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3, jointRisk: 3),
    notesJa: '運動量が非常に多い。暑い時間帯の長時間運動は注意。',
  ),
  Breed(
    id: 'german_shepherd',
    jaName: 'ジャーマン・シェパード・ドッグ',
    kana: 'じゃーまんしぇぱーどどっぐ',
    enName: 'German Shepherd Dog',
    aliases: ['シェパード', 'GSD', 'ジャーマンシェパード'],
    jkcGroup: '1G',
    akcGroup: 'Herding',
    sizeDefault: 'L',
    coatLength: '中毛',
    coatType: 'ダブル',
    exerciseLevel: 'high',
    risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3, jointRisk: 4, stomachRisk: 4),
    notesJa: '股関節形成不全・胃拡張に注意。運動後すぐの食事は避ける。',
  ),
  Breed(
    id: 'shetland_sheepdog',
    jaName: 'シェットランド・シープドッグ',
    kana: 'しぇっとらんどしーぷどっぐ',
    enName: 'Shetland Sheepdog',
    aliases: ['シェルティ', 'シェルティー'],
    jkcGroup: '1G',
    akcGroup: 'Herding',
    sizeDefault: 'S',
    coatLength: '長毛',
    coatType: 'ダブル',
    exerciseLevel: 'high',
    risk: BreedRisk(heatRisk: 4, coldRisk: 2, humidityRisk: 3, skinRisk: 3),
    notesJa: '被毛が厚く夏の暑さに注意。換毛期の毛玉にも気をつける。',
  ),
  Breed(
    id: 'rough_collie',
    jaName: 'コリー（ラフ）',
    kana: 'こりーらふ',
    enName: 'Rough Collie',
    aliases: ['ラフコリー', 'コリー'],
    jkcGroup: '1G',
    akcGroup: 'Herding',
    sizeDefault: 'L',
    coatLength: '長毛',
    coatType: 'ダブル',
    exerciseLevel: 'high',
    risk: BreedRisk(heatRisk: 4, coldRisk: 2, humidityRisk: 3, eyeRisk: 3),
    notesJa: '長毛で暑さに弱い傾向。目の疾患に注意されることがある。',
  ),
  Breed(
    id: 'welsh_corgi_pembroke',
    jaName: 'ウェルシュ・コーギー・ペンブローク',
    kana: 'うぇるしゅこーぎーぺんぶろーく',
    enName: 'Welsh Corgi Pembroke',
    aliases: ['コーギー', 'ペンブローク'],
    jkcGroup: '1G',
    akcGroup: 'Herding',
    sizeDefault: 'S',
    coatLength: '中毛',
    coatType: 'ダブル',
    exerciseLevel: 'high',
    risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3, jointRisk: 4, longBack: true),
    notesJa: '胴長短足で椎間板ヘルニアに注意。段差や階段の上り下りは慎重に。',
  ),
  Breed(
    id: 'australian_shepherd',
    jaName: 'オーストラリアン・シェパード',
    kana: 'おーすとらりあんしぇぱーど',
    enName: 'Australian Shepherd',
    aliases: ['オーシー', 'オージー', 'Aussie'],
    jkcGroup: '1G',
    akcGroup: 'Herding',
    sizeDefault: 'M',
    coatLength: '中毛',
    coatType: 'ダブル',
    exerciseLevel: 'very_high',
    risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3, eyeRisk: 3),
    notesJa: '運動量が非常に多い。目の疾患（MDR1遺伝子）に注意されることがある。',
  ),
];

// =============================
// JKC 2G：使役犬
// =============================
const List<Breed> jkc2gBreeds = [
  Breed(
    id: 'dobermann',
    jaName: 'ドーベルマン',
    kana: 'どーべるまん',
    enName: 'Dobermann',
    aliases: ['ドーベルマン'],
    jkcGroup: '2G',
    akcGroup: 'Working',
    sizeDefault: 'L',
    coatLength: '短毛',
    coatType: 'シングル',
    exerciseLevel: 'high',
    risk: BreedRisk(heatRisk: 3, coldRisk: 4, humidityRisk: 2, jointRisk: 3, stomachRisk: 4),
    notesJa: '短毛で寒さに弱い傾向。心臓疾患・胃拡張に注意されることがある。',
  ),
  Breed(
    id: 'rottweiler',
    jaName: 'ロットワイラー',
    kana: 'ろっとわいらー',
    enName: 'Rottweiler',
    aliases: ['ロット'],
    jkcGroup: '2G',
    akcGroup: 'Working',
    sizeDefault: 'L',
    coatLength: '短毛',
    coatType: 'ダブル',
    exerciseLevel: 'high',
    risk: BreedRisk(heatRisk: 4, coldRisk: 2, humidityRisk: 3, jointRisk: 4, stomachRisk: 4, giantBreed: true),
    notesJa: '大型犬で暑さに注意。股関節・胃拡張に注意されることがある。',
  ),
  Breed(
    id: 'great_dane',
    jaName: 'グレート・デーン',
    kana: 'ぐれーとでーん',
    enName: 'Great Dane',
    aliases: ['グレートデーン'],
    jkcGroup: '2G',
    akcGroup: 'Working',
    sizeDefault: 'XL',
    coatLength: '短毛',
    coatType: 'シングル',
    exerciseLevel: 'medium',
    risk: BreedRisk(heatRisk: 4, coldRisk: 3, humidityRisk: 3, jointRisk: 5, stomachRisk: 5, giantBreed: true),
    notesJa: '超大型犬で胃拡張・胃捻転のリスクに特に注意。食後の激しい運動は避ける。',
  ),
  Breed(
    id: 'bernese_mountain_dog',
    jaName: 'バーニーズ・マウンテン・ドッグ',
    kana: 'ばーにーずまうんてんどっぐ',
    enName: 'Bernese Mountain Dog',
    aliases: ['バーニーズ', 'バーニーズマウンテンドッグ', 'バーニ'],
    jkcGroup: '2G',
    akcGroup: 'Working',
    sizeDefault: 'XL',
    coatLength: '長毛',
    coatType: 'ダブル',
    exerciseLevel: 'medium',
    risk: BreedRisk(heatRisk: 5, coldRisk: 1, humidityRisk: 4, jointRisk: 5, stomachRisk: 4, giantBreed: true),
    notesJa: '暑さに非常に弱い。夏は特に注意が必要。股関節・肘関節に注意されることがある。',
  ),
  Breed(
    id: 'saint_bernard',
    jaName: 'セント・バーナード',
    kana: 'せんとばーなーど',
    enName: 'Saint Bernard',
    aliases: ['セントバーナード'],
    jkcGroup: '2G',
    akcGroup: 'Working',
    sizeDefault: 'XL',
    coatLength: '長毛',
    coatType: 'ダブル',
    exerciseLevel: 'low',
    risk: BreedRisk(heatRisk: 5, coldRisk: 1, humidityRisk: 4, jointRisk: 4, stomachRisk: 5, giantBreed: true),
    notesJa: '超大型犬で暑さに非常に弱い。胃拡張・胃捻転に特に注意。',
  ),
  Breed(
    id: 'boxer',
    jaName: 'ボクサー',
    kana: 'ぼくさー',
    enName: 'Boxer',
    aliases: ['ボクサー'],
    jkcGroup: '2G',
    akcGroup: 'Working',
    sizeDefault: 'L',
    coatLength: '短毛',
    coatType: 'シングル',
    exerciseLevel: 'high',
    risk: BreedRisk(heatRisk: 5, coldRisk: 3, humidityRisk: 4, respiratoryRisk: 5, shortNose: true),
    notesJa: '短頭種で暑さ・湿度に非常に弱い。気温が高い日の屋外運動は特に注意。',
  ),
];

// =============================
// JKC 3G：テリア
// =============================
const List<Breed> jkc3gBreeds = [
  Breed(
    id: 'yorkshire_terrier',
    jaName: 'ヨークシャー・テリア',
    kana: 'よーくしゃーてりあ',
    enName: 'Yorkshire Terrier',
    aliases: ['ヨーキー', 'ヨークシャテリア'],
    jkcGroup: '3G',
    akcGroup: 'Toy',
    sizeDefault: 'SS',
    coatLength: '長毛',
    coatType: 'シングル',
    exerciseLevel: 'medium',
    risk: BreedRisk(heatRisk: 3, coldRisk: 4, humidityRisk: 3, skinRisk: 3),
    notesJa: '小型で寒さに弱い傾向。被毛のお手入れが必要。',
  ),
  Breed(
    id: 'miniature_schnauzer',
    jaName: 'ミニチュア・シュナウザー',
    kana: 'みにちゅあしゅなうざー',
    enName: 'Miniature Schnauzer',
    aliases: ['シュナウザー', 'ミニシュナ'],
    jkcGroup: '3G',
    akcGroup: 'Terrier',
    sizeDefault: 'S',
    coatLength: '中毛',
    coatType: 'ワイヤー',
    exerciseLevel: 'medium',
    risk: BreedRisk(heatRisk: 3, coldRisk: 3, humidityRisk: 3, skinRisk: 3),
    notesJa: '膵炎・尿路結石に注意されることがある。定期的なトリミングが必要。',
  ),
  Breed(
    id: 'west_highland_white_terrier',
    jaName: 'ウエスト・ハイランド・ホワイト・テリア',
    kana: 'うえすとはいらんどほわいとてりあ',
    enName: 'West Highland White Terrier',
    aliases: ['ウェスティ', 'Westie'],
    jkcGroup: '3G',
    akcGroup: 'Terrier',
    sizeDefault: 'S',
    coatLength: '中毛',
    coatType: 'ダブル',
    exerciseLevel: 'medium',
    risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3, skinRisk: 4),
    notesJa: 'アトピー性皮膚炎に注意されることがある。',
  ),
];

// =============================
// JKC 4G：ダックスフンド
// =============================
const List<Breed> jkc4gBreeds = [
  Breed(
    id: 'dachshund_standard',
    jaName: 'ダックスフンド（スタンダード）',
    kana: 'だっくすふんどすたんだーど',
    enName: 'Standard Dachshund',
    aliases: ['ダックス', 'ダックスフンド', 'Dachshund'],
    jkcGroup: '4G',
    akcGroup: 'Hound',
    sizeDefault: 'S',
    coatLength: '短毛',
    coatType: 'シングル',
    exerciseLevel: 'medium',
    risk: BreedRisk(heatRisk: 3, coldRisk: 3, humidityRisk: 3, jointRisk: 5, longBack: true),
    notesJa: '胴長短足で椎間板ヘルニアに特に注意。段差・ジャンプはできるだけ避ける。',
  ),
  Breed(
    id: 'dachshund_miniature',
    jaName: 'ミニチュア・ダックスフンド',
    kana: 'みにちゅあだっくすふんど',
    enName: 'Miniature Dachshund',
    aliases: ['ミニダックス', 'ミニチュアダックス'],
    jkcGroup: '4G',
    akcGroup: 'Hound',
    sizeDefault: 'SS',
    coatLength: '短毛',
    coatType: 'シングル',
    exerciseLevel: 'medium',
    risk: BreedRisk(heatRisk: 3, coldRisk: 4, humidityRisk: 3, jointRisk: 5, longBack: true),
    notesJa: '椎間板ヘルニアに特に注意。小型で寒さにも注意が必要。',
  ),
];

// =============================
// JKC 5G：原始的な犬・スピッツ
// =============================
const List<Breed> jkc5gBreeds = [
  Breed(
    id: 'shiba',
    jaName: '柴犬',
    kana: 'しばいぬ',
    enName: 'Shiba Inu',
    aliases: ['柴犬', 'Shiba', '柴'],
    jkcGroup: '5G',
    akcGroup: 'Non-Sporting',
    sizeDefault: 'S',
    coatLength: '短毛',
    coatType: 'ダブル',
    exerciseLevel: 'high',
    risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3, skinRisk: 3),
    notesJa: 'アレルギー性皮膚炎に注意されることがある。換毛期の抜け毛が多い。',
  ),
  Breed(
    id: 'akita',
    jaName: '秋田犬',
    kana: 'あきたいぬ',
    enName: 'Akita',
    aliases: ['秋田犬', 'Akita Inu'],
    jkcGroup: '5G',
    akcGroup: 'Working',
    sizeDefault: 'XL',
    coatLength: '中毛',
    coatType: 'ダブル',
    exerciseLevel: 'medium',
    risk: BreedRisk(heatRisk: 4, coldRisk: 1, humidityRisk: 3, jointRisk: 3, giantBreed: true),
    notesJa: '大型で暑さに注意。免疫系の疾患に注意されることがある。',
  ),
  Breed(
    id: 'pomeranian',
    jaName: 'ポメラニアン',
    kana: 'ぽめらにあん',
    enName: 'Pomeranian',
    aliases: ['ポメラニアン'],
    jkcGroup: '5G',
    akcGroup: 'Toy',
    sizeDefault: 'SS',
    coatLength: '長毛',
    coatType: 'ダブル',
    exerciseLevel: 'medium',
    risk: BreedRisk(heatRisk: 4, coldRisk: 2, humidityRisk: 3, skinRisk: 3),
    notesJa: '被毛が厚く夏の暑さに注意。脱毛症（アロペシアX）に注意されることがある。',
  ),
  Breed(
    id: 'siberian_husky',
    jaName: 'シベリアン・ハスキー',
    kana: 'しべりあんはすきー',
    enName: 'Siberian Husky',
    aliases: ['ハスキー'],
    jkcGroup: '5G',
    akcGroup: 'Working',
    sizeDefault: 'M',
    coatLength: '中毛',
    coatType: 'ダブル',
    exerciseLevel: 'very_high',
    risk: BreedRisk(heatRisk: 5, coldRisk: 1, humidityRisk: 4, eyeRisk: 3),
    notesJa: '暑さに非常に弱い。夏の屋外運動は朝夕の涼しい時間帯に限定する。',
  ),
  Breed(
    id: 'samoyed',
    jaName: 'サモエド',
    kana: 'さもえど',
    enName: 'Samoyed',
    aliases: ['サモエド'],
    jkcGroup: '5G',
    akcGroup: 'Working',
    sizeDefault: 'L',
    coatLength: '長毛',
    coatType: 'ダブル',
    exerciseLevel: 'high',
    risk: BreedRisk(heatRisk: 5, coldRisk: 1, humidityRisk: 4, skinRisk: 3),
    notesJa: '暑さに非常に弱い。白い被毛は汚れやすく定期的なケアが必要。',
  ),
  Breed(
    id: 'japanese_spitz',
    jaName: '日本スピッツ',
    kana: 'にほんすぴっつ',
    enName: 'Japanese Spitz',
    aliases: ['スピッツ'],
    jkcGroup: '5G',
    akcGroup: '',
    sizeDefault: 'S',
    coatLength: '長毛',
    coatType: 'ダブル',
    exerciseLevel: 'medium',
    risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3),
    notesJa: '比較的丈夫な犬種。換毛期の抜け毛が多い。',
  ),
];

// =============================
// JKC 6G：嗅覚ハウンド
// =============================
const List<Breed> jkc6gBreeds = [
  Breed(
    id: 'beagle',
    jaName: 'ビーグル',
    kana: 'びーぐる',
    enName: 'Beagle',
    aliases: ['ビーグル'],
    jkcGroup: '6G',
    akcGroup: 'Hound',
    sizeDefault: 'S',
    coatLength: '短毛',
    coatType: 'ダブル',
    exerciseLevel: 'high',
    risk: BreedRisk(heatRisk: 3, coldRisk: 3, humidityRisk: 3, earRisk: 4),
    notesJa: '垂れ耳で耳の通気が悪く外耳炎に注意。においに敏感で脱走注意。',
  ),
  Breed(
    id: 'basset_hound',
    jaName: 'バセット・ハウンド',
    kana: 'ばせっとはうんど',
    enName: 'Basset Hound',
    aliases: ['バセット'],
    jkcGroup: '6G',
    akcGroup: 'Hound',
    sizeDefault: 'M',
    coatLength: '短毛',
    coatType: 'シングル',
    exerciseLevel: 'low',
    risk: BreedRisk(heatRisk: 4, coldRisk: 3, humidityRisk: 3, earRisk: 5, jointRisk: 3, longBack: true),
    notesJa: '耳が非常に長く外耳炎に特に注意。胴長で椎間板にも注意。',
  ),
];

// =============================
// JKC 7G：ポインター・セター
// =============================
const List<Breed> jkc7gBreeds = [
  Breed(
    id: 'english_setter',
    jaName: 'イングリッシュ・セター',
    kana: 'いんぐりっしゅせたー',
    enName: 'English Setter',
    aliases: ['セター'],
    jkcGroup: '7G',
    akcGroup: 'Sporting',
    sizeDefault: 'L',
    coatLength: '長毛',
    coatType: 'シングル',
    exerciseLevel: 'very_high',
    risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3, earRisk: 3),
    notesJa: '運動量が非常に多い。垂れ耳で外耳炎に注意。',
  ),
  Breed(
    id: 'pointer',
    jaName: 'ポインター',
    kana: 'ぽいんたー',
    enName: 'Pointer',
    aliases: ['ポインター'],
    jkcGroup: '7G',
    akcGroup: 'Sporting',
    sizeDefault: 'L',
    coatLength: '短毛',
    coatType: 'シングル',
    exerciseLevel: 'very_high',
    risk: BreedRisk(heatRisk: 3, coldRisk: 3, humidityRisk: 2),
    notesJa: '運動量が非常に多い。短毛で寒い時期は防寒に注意。',
  ),
];

// =============================
// JKC 8G：7G以外の鳥猟犬
// =============================
const List<Breed> jkc8gBreeds = [
  Breed(
    id: 'golden_retriever',
    jaName: 'ゴールデン・レトリーバー',
    kana: 'ごーるでんれとりーばー',
    enName: 'Golden Retriever',
    aliases: ['ゴールデン', 'ゴルレト', 'Golden'],
    jkcGroup: '8G',
    akcGroup: 'Sporting',
    sizeDefault: 'L',
    coatLength: '長毛',
    coatType: 'ダブル',
    exerciseLevel: 'high',
    risk: BreedRisk(heatRisk: 4, coldRisk: 2, humidityRisk: 3, jointRisk: 4, earRisk: 4, stomachRisk: 3),
    notesJa: '被毛が厚く暑さに注意。股関節・外耳炎に注意されることがある。',
  ),
  Breed(
    id: 'labrador_retriever',
    jaName: 'ラブラドール・レトリーバー',
    kana: 'らぶらどーるれとりーばー',
    enName: 'Labrador Retriever',
    aliases: ['ラブラドール', 'ラブ', 'Lab'],
    jkcGroup: '8G',
    akcGroup: 'Sporting',
    sizeDefault: 'L',
    coatLength: '短毛',
    coatType: 'ダブル',
    exerciseLevel: 'high',
    risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3, jointRisk: 4, stomachRisk: 3),
    notesJa: '食欲旺盛で肥満に注意。股関節形成不全に注意されることがある。',
  ),
  Breed(
    id: 'cocker_spaniel',
    jaName: 'コッカー・スパニエル',
    kana: 'こっかーすぱにえる',
    enName: 'Cocker Spaniel',
    aliases: ['コッカー', 'アメリカンコッカー'],
    jkcGroup: '8G',
    akcGroup: 'Sporting',
    sizeDefault: 'S',
    coatLength: '長毛',
    coatType: 'シングル',
    exerciseLevel: 'medium',
    risk: BreedRisk(heatRisk: 3, coldRisk: 3, humidityRisk: 3, earRisk: 5, eyeRisk: 3),
    notesJa: '垂れ耳で外耳炎に特に注意。定期的な耳のケアが必要。',
  ),
];

// =============================
// JKC 9G：愛玩犬
// =============================
const List<Breed> jkc9gBreeds = [
  Breed(
    id: 'poodle_toy',
    jaName: 'トイ・プードル',
    kana: 'といぷーどる',
    enName: 'Toy Poodle',
    aliases: ['トイプードル', 'プードル', 'Poodle'],
    jkcGroup: '9G',
    akcGroup: 'Non-Sporting',
    sizeDefault: 'SS',
    coatLength: '長毛',
    coatType: '巻き毛',
    exerciseLevel: 'medium',
    risk: BreedRisk(heatRisk: 3, coldRisk: 4, humidityRisk: 3, earRisk: 4, jointRisk: 3),
    notesJa: '小型で寒さに弱い傾向。垂れ耳で外耳炎・膝蓋骨脱臼に注意されることがある。',
  ),
  Breed(
    id: 'chihuahua',
    jaName: 'チワワ',
    kana: 'ちわわ',
    enName: 'Chihuahua',
    aliases: ['チワワ'],
    jkcGroup: '9G',
    akcGroup: 'Toy',
    sizeDefault: 'SS',
    coatLength: '短毛',
    coatType: 'シングル',
    exerciseLevel: 'low',
    risk: BreedRisk(heatRisk: 3, coldRisk: 5, humidityRisk: 3, jointRisk: 3),
    notesJa: '超小型で寒さに非常に弱い。低血糖に注意。骨が細く骨折に気をつける。',
  ),
  Breed(
    id: 'maltese',
    jaName: 'マルチーズ',
    kana: 'まるちーず',
    enName: 'Maltese',
    aliases: ['マルチーズ'],
    jkcGroup: '9G',
    akcGroup: 'Toy',
    sizeDefault: 'SS',
    coatLength: '長毛',
    coatType: 'シングル',
    exerciseLevel: 'low',
    risk: BreedRisk(heatRisk: 3, coldRisk: 4, humidityRisk: 3, skinRisk: 3, eyeRisk: 3),
    notesJa: '目やにによる涙やけに注意。皮膚が敏感な傾向がある。',
  ),
  Breed(
    id: 'shih_tzu',
    jaName: 'シー・ズー',
    kana: 'しーずー',
    enName: 'Shih Tzu',
    aliases: ['シーズー'],
    jkcGroup: '9G',
    akcGroup: 'Toy',
    sizeDefault: 'SS',
    coatLength: '長毛',
    coatType: 'ダブル',
    exerciseLevel: 'low',
    risk: BreedRisk(heatRisk: 4, coldRisk: 3, humidityRisk: 4, respiratoryRisk: 4, eyeRisk: 4, shortNose: true),
    notesJa: '短頭種で暑さ・湿度に注意。目が大きく目の疾患に注意されることがある。',
  ),
  Breed(
    id: 'pug',
    jaName: 'パグ',
    kana: 'ぱぐ',
    enName: 'Pug',
    aliases: ['パグ'],
    jkcGroup: '9G',
    akcGroup: 'Toy',
    sizeDefault: 'S',
    coatLength: '短毛',
    coatType: 'ダブル',
    exerciseLevel: 'low',
    risk: BreedRisk(heatRisk: 5, coldRisk: 3, humidityRisk: 5, respiratoryRisk: 5, eyeRisk: 4, shortNose: true),
    notesJa: '短頭種で暑さ・湿度に非常に弱い。気温が高い日の屋外は特に注意が必要。',
  ),
  Breed(
    id: 'french_bulldog',
    jaName: 'フレンチ・ブルドッグ',
    kana: 'ふれんちぶるどっぐ',
    enName: 'French Bulldog',
    aliases: ['フレブル', 'フレンチブルドッグ'],
    jkcGroup: '9G',
    akcGroup: 'Non-Sporting',
    sizeDefault: 'S',
    coatLength: '短毛',
    coatType: 'シングル',
    exerciseLevel: 'low',
    risk: BreedRisk(heatRisk: 5, coldRisk: 3, humidityRisk: 5, respiratoryRisk: 5, shortNose: true),
    notesJa: '短頭種で暑さ・湿度に非常に弱い。夏の散歩は朝夕の短時間に限定する。',
  ),
  Breed(
    id: 'cavalier_king_charles',
    jaName: 'キャバリア・キング・チャールズ・スパニエル',
    kana: 'きゃばりあきんぐちゃーるずすぱにえる',
    enName: 'Cavalier King Charles Spaniel',
    aliases: ['キャバリア', 'キャバ'],
    jkcGroup: '9G',
    akcGroup: 'Toy',
    sizeDefault: 'S',
    coatLength: '長毛',
    coatType: 'シングル',
    exerciseLevel: 'medium',
    risk: BreedRisk(heatRisk: 3, coldRisk: 3, humidityRisk: 3, earRisk: 4, eyeRisk: 3),
    notesJa: '心臓疾患（僧帽弁疾患）に注意されることがある。定期的な心臓チェックを推奨。',
  ),
  Breed(
    id: 'papillon',
    jaName: 'パピヨン',
    kana: 'ぱぴよん',
    enName: 'Papillon',
    aliases: ['パピヨン'],
    jkcGroup: '9G',
    akcGroup: 'Toy',
    sizeDefault: 'SS',
    coatLength: '長毛',
    coatType: 'シングル',
    exerciseLevel: 'medium',
    risk: BreedRisk(heatRisk: 3, coldRisk: 4, humidityRisk: 3, jointRisk: 3),
    notesJa: '小型で寒さに注意。膝蓋骨脱臼に注意されることがある。',
  ),
];

// =============================
// JKC 10G：視覚ハウンド
// =============================
const List<Breed> jkc10gBreeds = [
  Breed(
    id: 'greyhound',
    jaName: 'グレイハウンド',
    kana: 'ぐれいはうんど',
    enName: 'Greyhound',
    aliases: ['グレイハウンド'],
    jkcGroup: '10G',
    akcGroup: 'Hound',
    sizeDefault: 'L',
    coatLength: '短毛',
    coatType: 'シングル',
    exerciseLevel: 'high',
    risk: BreedRisk(heatRisk: 3, coldRisk: 4, humidityRisk: 2),
    notesJa: '短毛で体脂肪が少なく寒さに弱い。麻酔への感受性が高いため手術時は注意。',
  ),
  Breed(
    id: 'whippet',
    jaName: 'ウィペット',
    kana: 'うぃぺっと',
    enName: 'Whippet',
    aliases: ['ウィペット'],
    jkcGroup: '10G',
    akcGroup: 'Hound',
    sizeDefault: 'M',
    coatLength: '短毛',
    coatType: 'シングル',
    exerciseLevel: 'high',
    risk: BreedRisk(heatRisk: 3, coldRisk: 4, humidityRisk: 2),
    notesJa: '短毛で寒さに弱い傾向。素早い動きで関節への負担に注意。',
  ),
  Breed(id: 'mame_shiba', jaName: '豆柴', kana: 'まめしば', enName: 'Mame Shiba', aliases: ['まめしば', '豆柴犬'], jkcGroup: '5', akcGroup: 'Non-Sporting', sizeDefault: 'SS', coatLength: '短毛', coatType: 'ダブル', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3), notesJa: '柴犬の小型タイプ。丈夫だが暑さにはやや注意。'),
  Breed(id: 'nihon_terrier', jaName: '日本テリア', kana: 'にほんてりあ', enName: 'Nihon Terrier', aliases: ['ジャパニーズテリア'], jkcGroup: '3', akcGroup: 'Foundation Stock', sizeDefault: 'S', coatLength: '短毛', coatType: 'シングル', exerciseLevel: 'high', risk: BreedRisk(heatRisk: 3, coldRisk: 3, humidityRisk: 3), notesJa: '日本原産の小型テリア。希少犬種。'),
  Breed(id: 'ryukyu_dog', jaName: '琉球犬', kana: 'りゅうきゅうけん', enName: 'Ryukyu Ken', aliases: ['沖縄犬'], jkcGroup: '5', akcGroup: 'Foundation Stock', sizeDefault: 'M', coatLength: '短毛', coatType: 'シングル', exerciseLevel: 'high', risk: BreedRisk(heatRisk: 2, coldRisk: 3, humidityRisk: 2), notesJa: '沖縄原産。暑さに比較的強い。'),
  Breed(id: 'miniature_poodle', jaName: 'ミニチュア・プードル', kana: 'みにちゅあぷーどる', enName: 'Miniature Poodle', aliases: ['ミニプードル'], jkcGroup: '9', akcGroup: 'Non-Sporting', sizeDefault: 'S', coatLength: '長毛', coatType: '巻き毛', exerciseLevel: 'high', risk: BreedRisk(heatRisk: 3, coldRisk: 3, humidityRisk: 3, earRisk: 4), notesJa: 'トイとスタンダードの中間サイズ。耳の通気に注意。'),
  Breed(id: 'standard_poodle', jaName: 'スタンダード・プードル', kana: 'すたんだーどぷーどる', enName: 'Standard Poodle', aliases: ['スタンダードプードル'], jkcGroup: '9', akcGroup: 'Non-Sporting', sizeDefault: 'L', coatLength: '長毛', coatType: '巻き毛', exerciseLevel: 'high', risk: BreedRisk(heatRisk: 3, coldRisk: 3, humidityRisk: 3, jointRisk: 3, earRisk: 4, stomachRisk: 3), notesJa: '大型プードル。運動量が多く関節ケアも重要。'),
  Breed(id: 'silky_terrier', jaName: 'シルキー・テリア', kana: 'しるきーてりあ', enName: 'Silky Terrier', aliases: ['オーストラリアンシルキーテリア'], jkcGroup: '3', akcGroup: 'Toy', sizeDefault: 'SS', coatLength: '長毛', coatType: 'シングル', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 3, coldRisk: 3, humidityRisk: 3, earRisk: 3), notesJa: 'ヨークシャーに似た小型テリア。'),
  Breed(id: 'russian_toy', jaName: 'ロシアン・トイ', kana: 'ろしあんとい', enName: 'Russian Toy', aliases: ['ルースキートイ'], jkcGroup: '9', akcGroup: 'Toy', sizeDefault: 'SS', coatLength: '短毛', coatType: 'シングル', exerciseLevel: 'low', risk: BreedRisk(heatRisk: 3, coldRisk: 5, humidityRisk: 3, jointRisk: 4), notesJa: '世界最小級の犬種。極端に寒さに弱く骨折リスクも高い。'),
  Breed(id: 'english_toy_spaniel', jaName: 'イングリッシュ・トイ・スパニエル', kana: 'いんぐりっしゅといすぱにえる', enName: 'English Toy Spaniel', aliases: ['キングチャールズスパニエル'], jkcGroup: '9', akcGroup: 'Toy', sizeDefault: 'SS', coatLength: '長毛', coatType: 'シングル', exerciseLevel: 'low', risk: BreedRisk(heatRisk: 4, coldRisk: 3, humidityRisk: 4, respiratoryRisk: 4, eyeRisk: 4, shortNose: true), notesJa: '短頭種。暑さに弱く目のケアが必要。'),
  Breed(id: 'maltese_mix', jaName: 'マルチーズミックス', kana: 'まるちーずみっくす', enName: 'Maltese Mix', aliases: ['マルMix'], jkcGroup: '', akcGroup: 'Mixed', sizeDefault: 'SS', coatLength: '長毛', coatType: 'シングル', exerciseLevel: 'low', risk: BreedRisk(heatRisk: 3, coldRisk: 3, humidityRisk: 3, eyeRisk: 3, earRisk: 3), notesJa: 'マルチーズミックス。目と耳のケアが必要。'),
  Breed(id: 'japanese_chin', jaName: '狆', kana: 'ちん', enName: 'Japanese Chin', aliases: ['チン', '日本チン'], jkcGroup: '9', akcGroup: 'Toy', sizeDefault: 'SS', coatLength: '長毛', coatType: 'シングル', exerciseLevel: 'low', risk: BreedRisk(heatRisk: 4, coldRisk: 3, humidityRisk: 4, respiratoryRisk: 4, eyeRisk: 4, shortNose: true), notesJa: '日本の伝統的な愛玩犬。短頭種で暑さに弱い。'),
  Breed(id: 'pekingese', jaName: 'ペキニーズ', kana: 'ぺきにーず', enName: 'Pekingese', aliases: ['ペキン'], jkcGroup: '9', akcGroup: 'Toy', sizeDefault: 'S', coatLength: '長毛', coatType: 'ダブル', exerciseLevel: 'low', risk: BreedRisk(heatRisk: 5, coldRisk: 3, humidityRisk: 4, respiratoryRisk: 5, eyeRisk: 4, shortNose: true), notesJa: '極端な短頭種。夏の散歩は避けるべき。'),
  Breed(id: 'coton_de_tulear', jaName: 'コトン・ド・テュレアール', kana: 'ことんどてゅれあーる', enName: 'Coton de Tulear', aliases: ['コトン'], jkcGroup: '9', akcGroup: 'Non-Sporting', sizeDefault: 'SS', coatLength: '長毛', coatType: 'シングル', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 3, coldRisk: 3, humidityRisk: 3, earRisk: 3), notesJa: 'マダガスカル原産。綿のような白い被毛。'),
  Breed(id: 'lowchen', jaName: 'レーヴヒェン', kana: 'れーふひぇん', enName: 'Lowchen', aliases: ['小さなライオン犬'], jkcGroup: '9', akcGroup: 'Non-Sporting', sizeDefault: 'SS', coatLength: '長毛', coatType: 'シングル', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 3, coldRisk: 3, humidityRisk: 3), notesJa: '希少犬種。ライオンカットが特徴的。'),
  Breed(id: 'basenji', jaName: 'バセンジー', kana: 'ばせんじー', enName: 'Basenji', aliases: ['バセンジ'], jkcGroup: '5', akcGroup: 'Hound', sizeDefault: 'M', coatLength: '短毛', coatType: 'シングル', exerciseLevel: 'high', risk: BreedRisk(heatRisk: 2, coldRisk: 4, humidityRisk: 2), notesJa: 'アフリカ原産。吠えない犬種。寒さに弱い。'),
  Breed(id: 'icelandic_sheepdog', jaName: 'アイスランド・シープドッグ', kana: 'あいすらんどしーぷどっぐ', enName: 'Icelandic Sheepdog', aliases: ['アイスランディックシープドッグ'], jkcGroup: '5', akcGroup: 'Herding', sizeDefault: 'M', coatLength: '中毛', coatType: 'ダブル', exerciseLevel: 'high', risk: BreedRisk(heatRisk: 3, coldRisk: 1, humidityRisk: 3), notesJa: 'アイスランド原産。寒さに非常に強い。'),
  Breed(id: 'finnish_spitz', jaName: 'フィニッシュ・スピッツ', kana: 'ふぃにっしゅすぴっつ', enName: 'Finnish Spitz', aliases: ['フィンランドスピッツ'], jkcGroup: '5', akcGroup: 'Non-Sporting', sizeDefault: 'M', coatLength: '中毛', coatType: 'ダブル', exerciseLevel: 'high', risk: BreedRisk(heatRisk: 3, coldRisk: 1, humidityRisk: 3), notesJa: 'フィンランドの国犬。よく吠える猟犬。'),
  Breed(id: 'norwegian_elkhound', jaName: 'ノルウェジアン・エルクハウンド', kana: 'のるうぇじあんえるくはうんど', enName: 'Norwegian Elkhound', aliases: ['エルクハウンド'], jkcGroup: '5', akcGroup: 'Hound', sizeDefault: 'M', coatLength: '短毛', coatType: 'ダブル', exerciseLevel: 'high', risk: BreedRisk(heatRisk: 3, coldRisk: 1, humidityRisk: 3), notesJa: 'ノルウェー原産のスピッツ系猟犬。'),
  Breed(id: 'keeshond', jaName: 'キースホンド', kana: 'きーすほんど', enName: 'Keeshond', aliases: ['ケースホンド'], jkcGroup: '5', akcGroup: 'Non-Sporting', sizeDefault: 'M', coatLength: '長毛', coatType: 'ダブル', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 3, coldRisk: 1, humidityRisk: 3, skinRisk: 3), notesJa: 'オランダ原産のスピッツ系。ふわふわの被毛が特徴。'),
  Breed(id: 'chow_chow', jaName: 'チャウ・チャウ', kana: 'ちゃうちゃう', enName: 'Chow Chow', aliases: ['チャウチャウ'], jkcGroup: '5', akcGroup: 'Non-Sporting', sizeDefault: 'L', coatLength: '長毛', coatType: 'ダブル', exerciseLevel: 'low', risk: BreedRisk(heatRisk: 4, coldRisk: 2, humidityRisk: 4, skinRisk: 4, jointRisk: 3), notesJa: '青い舌が特徴。夏の熱中症と皮膚疾患に注意。'),
  Breed(id: 'shar_pei', jaName: 'シャー・ペイ', kana: 'しゃーぺい', enName: 'Shar Pei', aliases: ['シャーペイ', 'チャイニーズシャーペイ'], jkcGroup: '2', akcGroup: 'Non-Sporting', sizeDefault: 'L', coatLength: '短毛', coatType: 'シングル', exerciseLevel: 'low', risk: BreedRisk(heatRisk: 4, coldRisk: 3, humidityRisk: 4, skinRisk: 5, earRisk: 4, eyeRisk: 4), notesJa: 'しわが多く皮膚疾患が非常に多い犬種。'),
  Breed(id: 'shiba_long', jaName: '長毛柴犬', kana: 'ながけしばいぬ', enName: 'Long Coat Shiba', aliases: ['長毛柴', 'ロングコート柴'], jkcGroup: '5', akcGroup: 'Non-Sporting', sizeDefault: 'S', coatLength: '長毛', coatType: 'ダブル', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3, skinRisk: 3), notesJa: '長毛タイプの柴犬。被毛が密で夏は特にケアが必要。'),
  Breed(id: 'xoloitzcuintli', jaName: 'ショロイツクィントリ', kana: 'しょろいつくぃんとり', enName: 'Xoloitzcuintli', aliases: ['メキシカンヘアレスドッグ', 'ショロ'], jkcGroup: '5', akcGroup: 'Non-Sporting', sizeDefault: 'M', coatLength: '短毛', coatType: 'シングル', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 3, coldRisk: 5, humidityRisk: 2, skinRisk: 5), notesJa: '無毛種。皮膚の日焼けと寒さ対策が必須。'),
  Breed(id: 'finnish_lapphund', jaName: 'フィニッシュ・ラップフンド', kana: 'ふぃにっしゅらっぷふんど', enName: 'Finnish Lapphund', aliases: ['ラップフンド'], jkcGroup: '5', akcGroup: 'Herding', sizeDefault: 'M', coatLength: '長毛', coatType: 'ダブル', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 3, coldRisk: 1, humidityRisk: 3), notesJa: 'フィンランド原産。トナカイの放牧に使われた犬種。'),
  Breed(id: 'swedish_vallhund', jaName: 'スウェディッシュ・バルフンド', kana: 'すうぇでぃっしゅばるふんど', enName: 'Swedish Vallhund', aliases: ['バルフンド'], jkcGroup: '5', akcGroup: 'Herding', sizeDefault: 'S', coatLength: '短毛', coatType: 'ダブル', exerciseLevel: 'high', risk: BreedRisk(heatRisk: 3, coldRisk: 1, humidityRisk: 3, longBack: true), notesJa: 'コーギーに似たスウェーデンの牧羊犬。胴長に注意。'),
  Breed(id: 'old_english_sheepdog', jaName: 'オールド・イングリッシュ・シープドッグ', kana: 'おーるどいんぐりっしゅしーぷどっぐ', enName: 'Old English Sheepdog', aliases: ['ボブテイル', 'OES'], jkcGroup: '1', akcGroup: 'Herding', sizeDefault: 'XL', coatLength: '長毛', coatType: 'ダブル', exerciseLevel: 'high', risk: BreedRisk(heatRisk: 4, coldRisk: 1, humidityRisk: 4, skinRisk: 3, earRisk: 3, eyeRisk: 3, giantBreed: true), notesJa: 'もふもふの被毛で夏の熱中症に注意。定期トリミングが必須。'),
  Breed(id: 'briard', jaName: 'ブリアード', kana: 'ぶりあーど', enName: 'Briard', aliases: ['ベルジャンブリアード'], jkcGroup: '1', akcGroup: 'Herding', sizeDefault: 'XL', coatLength: '長毛', coatType: 'ダブル', exerciseLevel: 'high', risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3, jointRisk: 3, earRisk: 3, giantBreed: true), notesJa: 'フランス原産の大型牧羊犬。'),
  Breed(id: 'komondor', jaName: 'コモンドール', kana: 'こもんどーる', enName: 'Komondor', aliases: ['コモンドル'], jkcGroup: '1', akcGroup: 'Working', sizeDefault: 'XL', coatLength: '長毛', coatType: 'ダブル', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 4, coldRisk: 1, humidityRisk: 4, skinRisk: 4, earRisk: 4, giantBreed: true), notesJa: 'モップのような被毛が特徴。皮膚と耳の蒸れに注意。'),
  Breed(id: 'puli', jaName: 'プーリー', kana: 'ぷーりー', enName: 'Puli', aliases: ['プリー'], jkcGroup: '1', akcGroup: 'Herding', sizeDefault: 'M', coatLength: '長毛', coatType: 'ダブル', exerciseLevel: 'high', risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3, skinRisk: 4, earRisk: 4), notesJa: 'ハンガリー原産。ドレッドヘアのような被毛が特徴。'),
  Breed(id: 'entlebucher', jaName: 'エントレブッフ・マウンテン・ドッグ', kana: 'えんとれぶっふまうんてんどっぐ', enName: 'Entlebucher Mountain Dog', aliases: ['エントレブッフ'], jkcGroup: '2', akcGroup: 'Herding', sizeDefault: 'M', coatLength: '短毛', coatType: 'ダブル', exerciseLevel: 'very_high', risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3, jointRisk: 2), notesJa: 'スイス原産の牧羊犬。非常に活発。'),
  Breed(id: 'greater_swiss', jaName: 'グレーター・スイス・マウンテン・ドッグ', kana: 'ぐれーたーすいすまうんてんどっぐ', enName: 'Greater Swiss Mountain Dog', aliases: ['グレスイ', 'GSMD'], jkcGroup: '2', akcGroup: 'Working', sizeDefault: 'XL', coatLength: '短毛', coatType: 'ダブル', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 3, coldRisk: 1, humidityRisk: 3, jointRisk: 4, stomachRisk: 4, giantBreed: true), notesJa: 'スイス原産の大型犬。関節と胃拡張に注意。'),
  Breed(id: 'appenzeller', jaName: 'アッペンツェラー・ゼンネンフント', kana: 'あっぺんつぇらーぜんねんふんと', enName: 'Appenzeller Sennenhund', aliases: ['アッペンツェラー'], jkcGroup: '2', akcGroup: 'Foundation Stock', sizeDefault: 'L', coatLength: '短毛', coatType: 'ダブル', exerciseLevel: 'very_high', risk: BreedRisk(heatRisk: 3, coldRisk: 1, humidityRisk: 3, jointRisk: 3), notesJa: 'スイス原産。非常に活発で運動量が多い。'),
  Breed(id: 'black_russian_terrier', jaName: 'ブラック・ロシアン・テリア', kana: 'ぶらっくろしあんてりあ', enName: 'Black Russian Terrier', aliases: ['ブラックテリア'], jkcGroup: '2', akcGroup: 'Working', sizeDefault: 'XL', coatLength: '中毛', coatType: 'ダブル', exerciseLevel: 'high', risk: BreedRisk(heatRisk: 3, coldRisk: 1, humidityRisk: 3, jointRisk: 3, earRisk: 3, giantBreed: true), notesJa: 'ロシア原産の大型護衛犬。寒さに非常に強い。'),
  Breed(id: 'dogo_argentino', jaName: 'ドゴ・アルヘンティーノ', kana: 'どごあるへんてぃーの', enName: 'Dogo Argentino', aliases: ['アルゼンチンドゴ'], jkcGroup: '2', akcGroup: 'Working', sizeDefault: 'XL', coatLength: '短毛', coatType: 'シングル', exerciseLevel: 'high', risk: BreedRisk(heatRisk: 3, coldRisk: 3, humidityRisk: 3, jointRisk: 3, stomachRisk: 3, giantBreed: true), notesJa: 'アルゼンチン原産の大型狩猟犬。'),
  Breed(id: 'caucasian_shepherd', jaName: 'コーカサス・シェパード', kana: 'こーかさすしぇぱーど', enName: 'Caucasian Shepherd', aliases: ['コーカシアンシェパード'], jkcGroup: '2', akcGroup: 'Foundation Stock', sizeDefault: 'XL', coatLength: '長毛', coatType: 'ダブル', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 3, coldRisk: 1, humidityRisk: 3, jointRisk: 4, stomachRisk: 3, giantBreed: true), notesJa: '世界最大級の護衛犬。寒さに非常に強い。'),
  Breed(id: 'central_asian_shepherd', jaName: 'セントラル・アジアン・シェパード', kana: 'せんとらるあじあんしぇぱーど', enName: 'Central Asian Shepherd', aliases: ['アラバイ'], jkcGroup: '2', akcGroup: 'Foundation Stock', sizeDefault: 'XL', coatLength: '短毛', coatType: 'ダブル', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 2, coldRisk: 1, humidityRisk: 2, jointRisk: 4, stomachRisk: 3, giantBreed: true), notesJa: '中央アジア原産の護衛犬。暑さ寒さに強い。'),
  Breed(id: 'south_russian_ovcharka', jaName: 'サウス・ロシアン・オフチャルカ', kana: 'さうすろしあんおふちゃるか', enName: 'South Russian Ovcharka', aliases: ['ウクライナ牧羊犬'], jkcGroup: '1', akcGroup: 'Foundation Stock', sizeDefault: 'XL', coatLength: '長毛', coatType: 'ダブル', exerciseLevel: 'high', risk: BreedRisk(heatRisk: 3, coldRisk: 1, humidityRisk: 3, jointRisk: 3, giantBreed: true), notesJa: 'ロシア原産の大型牧羊犬。'),
  Breed(id: 'hug', jaName: 'ハグ', kana: 'はぐ', enName: 'Hug', aliases: ['ハスキープー'], jkcGroup: '', akcGroup: 'Mixed', sizeDefault: 'M', coatLength: '中毛', coatType: 'ダブル', exerciseLevel: 'high', risk: BreedRisk(heatRisk: 4, coldRisk: 1, humidityRisk: 3, respiratoryRisk: 3), notesJa: 'ハスキー×パグ。短頭傾向と暑さに注意。'),
  Breed(id: 'jug', jaName: 'ジャグ', kana: 'じゃぐ', enName: 'Jug', aliases: ['ジャックパグ'], jkcGroup: '', akcGroup: 'Mixed', sizeDefault: 'S', coatLength: '短毛', coatType: 'シングル', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 4, coldRisk: 3, humidityRisk: 4, respiratoryRisk: 4, shortNose: true), notesJa: 'ジャックラッセル×パグ。短頭傾向あり。'),
  Breed(id: 'puggle', jaName: 'パグル', kana: 'ぱぐる', enName: 'Puggle', aliases: ['パグビーグル'], jkcGroup: '', akcGroup: 'Mixed', sizeDefault: 'S', coatLength: '短毛', coatType: 'シングル', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 4, coldRisk: 3, humidityRisk: 4, respiratoryRisk: 4, shortNose: true), notesJa: 'パグ×ビーグル。短頭傾向あり。'),
  Breed(id: 'dachshund_mix', jaName: 'ダックスミックス', kana: 'だっくすみっくす', enName: 'Dachshund Mix', aliases: ['ダックスMix'], jkcGroup: '', akcGroup: 'Mixed', sizeDefault: 'SS', coatLength: '短毛', coatType: 'シングル', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 3, coldRisk: 3, humidityRisk: 3, jointRisk: 4, longBack: true), notesJa: 'ダックスミックス。胴長なので腰の管理が重要。'),
  Breed(id: 'irish_water_spaniel', jaName: 'アイリッシュ・ウォーター・スパニエル', kana: 'あいりっしゅうぉーたーすぱにえる', enName: 'Irish Water Spaniel', aliases: ['ウォータースパニエル'], jkcGroup: '8', akcGroup: 'Sporting', sizeDefault: 'L', coatLength: '中毛', coatType: '巻き毛', exerciseLevel: 'very_high', risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3, earRisk: 4), notesJa: 'アイルランド原産の水猟犬。泳ぎが得意で非常に活発。'),
];

// =============================
// AKC専用（JKC未公認）
// =============================
const List<Breed> akcOnlyBreeds = [
  Breed(
    id: 'golden_doodle',
    jaName: 'ゴールデンドゥードル',
    kana: 'ごーるでんどぅーどる',
    enName: 'Goldendoodle',
    aliases: ['ゴールデンドゥードル', 'Goldendoodle'],
    jkcGroup: '',
    akcGroup: 'Miscellaneous',
    sizeDefault: 'L',
    coatLength: '長毛',
    coatType: '巻き毛',
    exerciseLevel: 'high',
    risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3, earRisk: 4),
    notesJa: 'ゴールデンとプードルのミックス。垂れ耳で外耳炎に注意。',
  ),
  Breed(id: 'jack_russell', jaName: 'ジャック・ラッセル・テリア', kana: 'じゃっくらっせるてりあ', enName: 'Jack Russell Terrier', aliases: ['JRT', 'ジャックラッセル'], jkcGroup: '3', akcGroup: 'Terrier', sizeDefault: 'S', coatLength: '短毛', coatType: 'シングル', exerciseLevel: 'very_high', risk: BreedRisk(heatRisk: 3, coldRisk: 3, humidityRisk: 3, jointRisk: 2), notesJa: '非常にエネルギッシュ。運動不足はストレスの原因に。'),
  Breed(id: 'bichon_frise', jaName: 'ビション・フリーゼ', kana: 'びしょんふりーぜ', enName: 'Bichon Frise', aliases: ['ビションフリーゼ'], jkcGroup: '9', akcGroup: 'Non-Sporting', sizeDefault: 'S', coatLength: '長毛', coatType: '巻き毛', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 3, coldRisk: 3, humidityRisk: 3, skinRisk: 3, earRisk: 3), notesJa: '白いふわふわの被毛。定期トリミングが必要。'),
  Breed(id: 'havanese', jaName: 'ハバニーズ', kana: 'はばにーず', enName: 'Havanese', aliases: ['ハバネーゼ'], jkcGroup: '9', akcGroup: 'Toy', sizeDefault: 'S', coatLength: '長毛', coatType: 'シングル', exerciseLevel: 'low', risk: BreedRisk(heatRisk: 3, coldRisk: 3, humidityRisk: 3, earRisk: 3, eyeRisk: 3), notesJa: 'キューバ原産の愛玩犬。穏やかで飼いやすい。'),
  Breed(id: 'scottish_terrier', jaName: 'スコティッシュ・テリア', kana: 'すこてぃっしゅてりあ', enName: 'Scottish Terrier', aliases: ['スコッチテリア', 'スコッティ'], jkcGroup: '3', akcGroup: 'Terrier', sizeDefault: 'S', coatLength: '中毛', coatType: 'ワイヤー', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3, skinRisk: 3), notesJa: '独立心が強い。皮膚疾患に注意。'),
  Breed(id: 'cairn_terrier', jaName: 'ケアーン・テリア', kana: 'けあーんてりあ', enName: 'Cairn Terrier', aliases: ['ケアンテリア'], jkcGroup: '3', akcGroup: 'Terrier', sizeDefault: 'S', coatLength: '短毛', coatType: 'ワイヤー', exerciseLevel: 'high', risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3), notesJa: 'オズの魔法使いのトトの犬種。丈夫で活発。'),
  Breed(id: 'norfolk_terrier', jaName: 'ノーフォーク・テリア', kana: 'のーふぉーくてりあ', enName: 'Norfolk Terrier', aliases: ['ノーフォークテリア'], jkcGroup: '3', akcGroup: 'Terrier', sizeDefault: 'SS', coatLength: '短毛', coatType: 'ワイヤー', exerciseLevel: 'high', risk: BreedRisk(heatRisk: 3, coldRisk: 3, humidityRisk: 3), notesJa: '小さいが活発なテリア。'),
  Breed(id: 'toy_fox_terrier', jaName: 'トイ・フォックス・テリア', kana: 'といふぉっくすてりあ', enName: 'Toy Fox Terrier', aliases: ['トイフォックステリア'], jkcGroup: '3', akcGroup: 'Toy', sizeDefault: 'SS', coatLength: '短毛', coatType: 'シングル', exerciseLevel: 'high', risk: BreedRisk(heatRisk: 3, coldRisk: 4, humidityRisk: 3, jointRisk: 3), notesJa: '小型で活発。寒さに弱い。'),
  Breed(id: 'chinese_crested', jaName: 'チャイニーズ・クレステッド', kana: 'ちゃいにーずくれすてっど', enName: 'Chinese Crested', aliases: ['チャイクレ'], jkcGroup: '9', akcGroup: 'Toy', sizeDefault: 'SS', coatLength: '短毛', coatType: 'シングル', exerciseLevel: 'low', risk: BreedRisk(heatRisk: 3, coldRisk: 5, humidityRisk: 2, skinRisk: 5), notesJa: '無毛種。皮膚の保護と防寒が必須。'),
  Breed(id: 'affenpinscher', jaName: 'アーフェンピンシャー', kana: 'あーふぇんぴんしゃー', enName: 'Affenpinscher', aliases: ['アフェンピンシャー'], jkcGroup: '2', akcGroup: 'Toy', sizeDefault: 'SS', coatLength: '短毛', coatType: 'ワイヤー', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 3, coldRisk: 3, humidityRisk: 3, respiratoryRisk: 3, shortNose: true), notesJa: '猿のような顔が特徴。短頭種。'),
  Breed(id: 'brussels_griffon', jaName: 'ブリュッセル・グリフォン', kana: 'ぶりゅっせるぐりふぉん', enName: 'Brussels Griffon', aliases: ['グリフォン'], jkcGroup: '9', akcGroup: 'Toy', sizeDefault: 'SS', coatLength: '短毛', coatType: 'ワイヤー', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 4, coldRisk: 3, humidityRisk: 4, respiratoryRisk: 4, eyeRisk: 4, shortNose: true), notesJa: '短頭種。目が大きく傷つきやすい。'),
  Breed(id: 'lhasa_apso', jaName: 'ラサ・アプソ', kana: 'らさあぷそ', enName: 'Lhasa Apso', aliases: ['ラサアプソ'], jkcGroup: '9', akcGroup: 'Non-Sporting', sizeDefault: 'S', coatLength: '長毛', coatType: 'ダブル', exerciseLevel: 'low', risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3, earRisk: 3, eyeRisk: 3), notesJa: 'チベット原産。長い被毛のお手入れが必要。'),
  Breed(id: 'tibetan_spaniel', jaName: 'チベタン・スパニエル', kana: 'ちべたんすぱにえる', enName: 'Tibetan Spaniel', aliases: ['チベタンスパニエル'], jkcGroup: '9', akcGroup: 'Non-Sporting', sizeDefault: 'S', coatLength: '中毛', coatType: 'ダブル', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3), notesJa: 'チベット原産の古い犬種。'),
  Breed(id: 'standard_schnauzer', jaName: 'スタンダード・シュナウザー', kana: 'すたんだーどしゅなうざー', enName: 'Standard Schnauzer', aliases: ['スタンダードシュナウザー'], jkcGroup: '2', akcGroup: 'Working', sizeDefault: 'M', coatLength: '短毛', coatType: 'ワイヤー', exerciseLevel: 'high', risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3, skinRisk: 3), notesJa: '頭が良く活発。定期トリミングが必要。'),
  Breed(id: 'giant_schnauzer', jaName: 'ジャイアント・シュナウザー', kana: 'じゃいあんとしゅなうざー', enName: 'Giant Schnauzer', aliases: ['ジャイアントシュナウザー'], jkcGroup: '2', akcGroup: 'Working', sizeDefault: 'XL', coatLength: '短毛', coatType: 'ワイヤー', exerciseLevel: 'very_high', risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3, jointRisk: 3, stomachRisk: 4, giantBreed: true), notesJa: '大型で活発。胃拡張に注意。'),
  Breed(id: 'springer_spaniel', jaName: 'イングリッシュ・スプリンガー・スパニエル', kana: 'いんぐりっしゅすぷりんがーすぱにえる', enName: 'English Springer Spaniel', aliases: ['スプリンガー'], jkcGroup: '8', akcGroup: 'Sporting', sizeDefault: 'M', coatLength: '中毛', coatType: 'ダブル', exerciseLevel: 'very_high', risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3, earRisk: 4), notesJa: '非常に活発。垂れ耳で外耳炎に注意。'),
  Breed(id: 'brittany', jaName: 'ブリタニー', kana: 'ぶりたにー', enName: 'Brittany', aliases: ['ブルターニュ'], jkcGroup: '7', akcGroup: 'Sporting', sizeDefault: 'M', coatLength: '中毛', coatType: 'ダブル', exerciseLevel: 'very_high', risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3, earRisk: 3), notesJa: 'フランス原産の猟犬。非常に活発。'),
  Breed(id: 'american_cocker_spaniel', jaName: 'アメリカン・コッカー・スパニエル', kana: 'あめりかんこっかーすぱにえる', enName: 'American Cocker Spaniel', aliases: ['アメコカ'], jkcGroup: '8', akcGroup: 'Sporting', sizeDefault: 'M', coatLength: '長毛', coatType: 'シングル', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 3, coldRisk: 3, humidityRisk: 3, earRisk: 5, eyeRisk: 3), notesJa: '耳の疾患が非常に多い犬種。定期的な耳掃除が必須。'),
  Breed(id: 'flat_coated_retriever', jaName: 'フラットコーテッド・レトリーバー', kana: 'ふらっとこーてっどれとりーばー', enName: 'Flat-Coated Retriever', aliases: ['フラットコート'], jkcGroup: '8', akcGroup: 'Sporting', sizeDefault: 'L', coatLength: '中毛', coatType: 'シングル', exerciseLevel: 'very_high', risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3, jointRisk: 3, stomachRisk: 3), notesJa: '非常に陽気で活発。'),
  Breed(id: 'nova_scotia', jaName: 'ノバ・スコシア・ダック・トーリング・レトリーバー', kana: 'のばすこしあだっくとーりんぐれとりーばー', enName: 'Nova Scotia Duck Tolling Retriever', aliases: ['トーラー', 'NSDTR'], jkcGroup: '8', akcGroup: 'Sporting', sizeDefault: 'M', coatLength: '中毛', coatType: 'ダブル', exerciseLevel: 'very_high', risk: BreedRisk(heatRisk: 3, coldRisk: 1, humidityRisk: 3, jointRisk: 2), notesJa: 'カナダ原産。非常に活発で泳ぎが得意。'),
  Breed(id: 'portuguese_water_dog', jaName: 'ポルトガル・ウォーター・ドッグ', kana: 'ぽるとがるうぉーたーどっぐ', enName: 'Portuguese Water Dog', aliases: ['ポーチュギーズウォータードッグ', 'PWD'], jkcGroup: '8', akcGroup: 'Working', sizeDefault: 'M', coatLength: '中毛', coatType: '巻き毛', exerciseLevel: 'very_high', risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3, earRisk: 3), notesJa: 'オバマ元大統領の愛犬として有名。水が大好き。'),
  Breed(id: 'harrier', jaName: 'ハリアー', kana: 'はりあー', enName: 'Harrier', aliases: ['ハリア'], jkcGroup: '6', akcGroup: 'Hound', sizeDefault: 'M', coatLength: '短毛', coatType: 'シングル', exerciseLevel: 'very_high', risk: BreedRisk(heatRisk: 3, coldRisk: 3, humidityRisk: 3), notesJa: 'ビーグルに似た猟犬。非常に活発。'),
  Breed(id: 'american_foxhound', jaName: 'アメリカン・フォックスハウンド', kana: 'あめりかんふぉっくすはうんど', enName: 'American Foxhound', aliases: ['フォックスハウンド'], jkcGroup: '6', akcGroup: 'Hound', sizeDefault: 'L', coatLength: '短毛', coatType: 'シングル', exerciseLevel: 'very_high', risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3, earRisk: 3), notesJa: '非常に活発な猟犬。'),
  Breed(id: 'plott_hound', jaName: 'プロット・ハウンド', kana: 'ぷろっとはうんど', enName: 'Plott Hound', aliases: ['プロットハウンド'], jkcGroup: '6', akcGroup: 'Hound', sizeDefault: 'L', coatLength: '短毛', coatType: 'シングル', exerciseLevel: 'very_high', risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3), notesJa: 'ノースカロライナ州の州犬。'),
  Breed(id: 'rhodesian_ridgeback', jaName: 'ローデシアン・リッジバック', kana: 'ろーでしあんりっじばっく', enName: 'Rhodesian Ridgeback', aliases: ['リッジバック'], jkcGroup: '6', akcGroup: 'Hound', sizeDefault: 'XL', coatLength: '短毛', coatType: 'シングル', exerciseLevel: 'very_high', risk: BreedRisk(heatRisk: 2, coldRisk: 3, humidityRisk: 2, jointRisk: 3, stomachRisk: 3, giantBreed: true), notesJa: 'アフリカ原産。暑さに強いが大型なので関節注意。'),
  Breed(id: 'pharaoh_hound', jaName: 'ファラオ・ハウンド', kana: 'ふぁらおはうんど', enName: 'Pharaoh Hound', aliases: ['ファラオハウンド'], jkcGroup: '5', akcGroup: 'Hound', sizeDefault: 'L', coatLength: '短毛', coatType: 'シングル', exerciseLevel: 'very_high', risk: BreedRisk(heatRisk: 2, coldRisk: 4, humidityRisk: 2, skinRisk: 3), notesJa: 'マルタ島原産。非常に古い犬種。寒さに弱い。'),
  Breed(id: 'alaskan_malamute', jaName: 'アラスカン・マラミュート', kana: 'あらすかんまらみゅーと', enName: 'Alaskan Malamute', aliases: ['マラミュート'], jkcGroup: '5', akcGroup: 'Working', sizeDefault: 'XL', coatLength: '長毛', coatType: 'ダブル', exerciseLevel: 'very_high', risk: BreedRisk(heatRisk: 5, coldRisk: 1, humidityRisk: 4, jointRisk: 4, stomachRisk: 3, giantBreed: true), notesJa: 'ハスキーより大型。夏の散歩は非常に危険。'),
  Breed(id: 'belgian_malinois', jaName: 'ベルジアン・マリノワ', kana: 'べるじあんまりのわ', enName: 'Belgian Malinois', aliases: ['マリノワ', 'ベルジャンマリノワ'], jkcGroup: '1', akcGroup: 'Herding', sizeDefault: 'L', coatLength: '短毛', coatType: 'ダブル', exerciseLevel: 'very_high', risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3, jointRisk: 2), notesJa: '警察犬として有名。非常に高い運動能力。'),
  Breed(id: 'belgian_tervuren', jaName: 'ベルジアン・タービュレン', kana: 'べるじあんたーびゅれん', enName: 'Belgian Tervuren', aliases: ['タービュレン'], jkcGroup: '1', akcGroup: 'Herding', sizeDefault: 'L', coatLength: '長毛', coatType: 'ダブル', exerciseLevel: 'very_high', risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3, jointRisk: 2), notesJa: 'ベルギー原産の牧羊犬。活発で賢い。'),
  Breed(id: 'bouvier_des_flandres', jaName: 'ブービエ・デ・フランドル', kana: 'ぶーびえでふらんどる', enName: 'Bouvier des Flandres', aliases: ['ブービエ'], jkcGroup: '1', akcGroup: 'Herding', sizeDefault: 'XL', coatLength: '中毛', coatType: 'ワイヤー', exerciseLevel: 'high', risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3, jointRisk: 3, stomachRisk: 3, giantBreed: true), notesJa: 'ベルギー原産の大型牧羊犬。'),
  Breed(id: 'cane_corso', jaName: 'ケイン・コルソ', kana: 'けいんこるそ', enName: 'Cane Corso', aliases: ['カネコルソ'], jkcGroup: '2', akcGroup: 'Working', sizeDefault: 'XL', coatLength: '短毛', coatType: 'シングル', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 3, coldRisk: 3, humidityRisk: 4, respiratoryRisk: 3, jointRisk: 4, stomachRisk: 4, shortNose: true, giantBreed: true), notesJa: 'イタリア原産の大型護衛犬。関節と胃拡張に注意。'),
  Breed(id: 'dogue_de_bordeaux', jaName: 'ドーグ・ド・ボルドー', kana: 'どーぐどぼるどー', enName: 'Dogue de Bordeaux', aliases: ['フレンチマスティフ'], jkcGroup: '2', akcGroup: 'Working', sizeDefault: 'XL', coatLength: '短毛', coatType: 'シングル', exerciseLevel: 'low', risk: BreedRisk(heatRisk: 5, coldRisk: 3, humidityRisk: 5, respiratoryRisk: 5, jointRisk: 5, stomachRisk: 4, shortNose: true, giantBreed: true), notesJa: '短頭種の超大型犬。夏の散歩は非常に危険。'),
  Breed(id: 'bullmastiff', jaName: 'ブルマスティフ', kana: 'ぶるますてぃふ', enName: 'Bullmastiff', aliases: ['ブルマスチフ'], jkcGroup: '2', akcGroup: 'Working', sizeDefault: 'XL', coatLength: '短毛', coatType: 'シングル', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 4, coldRisk: 3, humidityRisk: 4, respiratoryRisk: 4, jointRisk: 4, stomachRisk: 3, shortNose: true, giantBreed: true), notesJa: '大型短頭種。夏の管理が重要。'),
  Breed(id: 'tibetan_mastiff', jaName: 'チベタン・マスティフ', kana: 'ちべたんますてぃふ', enName: 'Tibetan Mastiff', aliases: ['チベットマスティフ'], jkcGroup: '2', akcGroup: 'Working', sizeDefault: 'XL', coatLength: '長毛', coatType: 'ダブル', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 4, coldRisk: 1, humidityRisk: 3, jointRisk: 4, stomachRisk: 3, giantBreed: true), notesJa: 'チベット原産の超大型犬。夏の熱中症に注意。'),
  Breed(id: 'anatolian_shepherd', jaName: 'アナトリアン・シェパード', kana: 'あなとりあんしぇぱーど', enName: 'Anatolian Shepherd', aliases: ['アナトリアン'], jkcGroup: '2', akcGroup: 'Working', sizeDefault: 'XL', coatLength: '短毛', coatType: 'ダブル', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 2, coldRisk: 2, humidityRisk: 2, jointRisk: 4, stomachRisk: 3, giantBreed: true), notesJa: 'トルコ原産の護衛犬。暑さに比較的強い。'),
  Breed(id: 'kangal', jaName: 'カンガル', kana: 'かんがる', enName: 'Kangal', aliases: ['カンガル・シェパード'], jkcGroup: '2', akcGroup: 'Working', sizeDefault: 'XL', coatLength: '短毛', coatType: 'ダブル', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 2, coldRisk: 2, humidityRisk: 2, jointRisk: 4, stomachRisk: 3, giantBreed: true), notesJa: 'トルコの国犬。世界最強の噛む力を持つ。'),
  Breed(id: 'belgian_sheepdog', jaName: 'ベルジアン・シープドッグ', kana: 'べるじあんしーぷどっぐ', enName: 'Belgian Sheepdog', aliases: ['グロネンダール'], jkcGroup: '1', akcGroup: 'Herding', sizeDefault: 'L', coatLength: '長毛', coatType: 'ダブル', exerciseLevel: 'very_high', risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3, jointRisk: 2), notesJa: '全身真っ黒のベルギー牧羊犬。'),
  Breed(id: 'chesapeake_bay', jaName: 'チェサピーク・ベイ・レトリーバー', kana: 'ちぇさぴーくべいれとりーばー', enName: 'Chesapeake Bay Retriever', aliases: ['チェサピーク'], jkcGroup: '8', akcGroup: 'Sporting', sizeDefault: 'L', coatLength: '短毛', coatType: 'ダブル', exerciseLevel: 'very_high', risk: BreedRisk(heatRisk: 3, coldRisk: 1, humidityRisk: 3, jointRisk: 3), notesJa: '寒冷地の水辺で活躍する猟犬。非常に活発。'),
  Breed(id: 'curly_coated_retriever', jaName: 'カーリーコーテッド・レトリーバー', kana: 'かーりーこーてっどれとりーばー', enName: 'Curly-Coated Retriever', aliases: ['カーリーコート'], jkcGroup: '8', akcGroup: 'Sporting', sizeDefault: 'L', coatLength: '短毛', coatType: '巻き毛', exerciseLevel: 'very_high', risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3, jointRisk: 3), notesJa: 'レトリーバーの中で最も古い犬種のひとつ。'),
  Breed(id: 'ponsky', jaName: 'ポンスキー', kana: 'ぽんすきー', enName: 'Pomsky', aliases: ['ポムスキー'], jkcGroup: '', akcGroup: 'Mixed', sizeDefault: 'S', coatLength: '長毛', coatType: 'ダブル', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 3, coldRisk: 1, humidityRisk: 3, jointRisk: 2), notesJa: 'ポメラニアン×ハスキー。ふわふわで人気のミックス。'),
  Breed(id: 'corgi_doodle', jaName: 'コーギードール', kana: 'こーぎーどーる', enName: 'Corgipoo', aliases: ['コーギープー', 'Corgipoo'], jkcGroup: '', akcGroup: 'Mixed', sizeDefault: 'S', coatLength: '中毛', coatType: '巻き毛', exerciseLevel: 'high', risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3, jointRisk: 3, longBack: true), notesJa: 'コーギー×プードル。胴長なので腰に注意。'),
  Breed(id: 'schnoodle', jaName: 'シュナプー', kana: 'しゅなぷー', enName: 'Schnoodle', aliases: ['シュヌードル'], jkcGroup: '', akcGroup: 'Mixed', sizeDefault: 'S', coatLength: '中毛', coatType: '巻き毛', exerciseLevel: 'high', risk: BreedRisk(heatRisk: 3, coldRisk: 3, humidityRisk: 3, earRisk: 3, skinRisk: 3), notesJa: 'シュナウザー×プードル。賢くて活発。'),
  Breed(id: 'yorkipoo', jaName: 'ヨーキープー', kana: 'よーきーぷー', enName: 'Yorkipoo', aliases: ['ヨーキプー'], jkcGroup: '', akcGroup: 'Mixed', sizeDefault: 'SS', coatLength: '長毛', coatType: '巻き毛', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 3, coldRisk: 3, humidityRisk: 3, jointRisk: 3, earRisk: 3), notesJa: 'ヨークシャー×プードル。膝蓋骨脱臼に注意。'),
  Breed(id: 'sheepadoodle', jaName: 'シープドゥードル', kana: 'しーぷどぅーどる', enName: 'Sheepadoodle', aliases: ['シープドードル'], jkcGroup: '', akcGroup: 'Mixed', sizeDefault: 'XL', coatLength: '中毛', coatType: '巻き毛', exerciseLevel: 'high', risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3, jointRisk: 3, earRisk: 3, giantBreed: true), notesJa: 'オールドイングリッシュシープドッグ×プードル。'),
  Breed(id: 'aussiedoodle', jaName: 'オージードゥードル', kana: 'おーじーどぅーどる', enName: 'Aussiedoodle', aliases: ['オーシードゥードル'], jkcGroup: '', akcGroup: 'Mixed', sizeDefault: 'M', coatLength: '中毛', coatType: '巻き毛', exerciseLevel: 'very_high', risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3, earRisk: 3, eyeRisk: 3), notesJa: 'オーストラリアンシェパード×プードル。非常に賢い。'),
  Breed(id: 'huskydoodle', jaName: 'ハスキードゥードル', kana: 'はすきーどぅーどる', enName: 'Huskydoodle', aliases: ['シベリアンプードル'], jkcGroup: '', akcGroup: 'Mixed', sizeDefault: 'L', coatLength: '中毛', coatType: '巻き毛', exerciseLevel: 'very_high', risk: BreedRisk(heatRisk: 4, coldRisk: 1, humidityRisk: 3, jointRisk: 2, earRisk: 3), notesJa: 'ハスキー×プードル。夏の散歩は特に注意。'),
  Breed(id: 'goberian', jaName: 'ゴベリアン', kana: 'ごべりあん', enName: 'Goberian', aliases: ['ゴールデンハスキー'], jkcGroup: '', akcGroup: 'Mixed', sizeDefault: 'L', coatLength: '中毛', coatType: 'ダブル', exerciseLevel: 'very_high', risk: BreedRisk(heatRisk: 4, coldRisk: 1, humidityRisk: 3, jointRisk: 3, earRisk: 3), notesJa: 'ゴールデン×ハスキー。夏の暑さに注意。'),
  Breed(id: 'frenchton', jaName: 'フレンチトン', kana: 'ふれんちとん', enName: 'Frenchton', aliases: ['フレンチトン'], jkcGroup: '', akcGroup: 'Mixed', sizeDefault: 'S', coatLength: '短毛', coatType: 'シングル', exerciseLevel: 'low', risk: BreedRisk(heatRisk: 5, coldRisk: 3, humidityRisk: 5, respiratoryRisk: 5, eyeRisk: 4, shortNose: true), notesJa: 'フレンチブル×ボストンテリア。短頭種で夏は非常に危険。'),
  Breed(id: 'pomchi', jaName: 'ポムチー', kana: 'ぽむちー', enName: 'Pomchi', aliases: ['ポメチワ'], jkcGroup: '', akcGroup: 'Mixed', sizeDefault: 'SS', coatLength: '長毛', coatType: 'ダブル', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 3, coldRisk: 3, humidityRisk: 3, jointRisk: 3), notesJa: 'ポメラニアン×チワワ。小型で繊細。'),
  Breed(id: 'chiweenie', jaName: 'チウィーニー', kana: 'ちうぃーにー', enName: 'Chiweenie', aliases: ['チワックス'], jkcGroup: '', akcGroup: 'Mixed', sizeDefault: 'SS', coatLength: '短毛', coatType: 'シングル', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 3, coldRisk: 4, humidityRisk: 3, jointRisk: 3, longBack: true), notesJa: 'チワワ×ダックスフンド。胴長なので腰に注意。'),
  Breed(id: 'shorkie', jaName: 'ショーキー', kana: 'しょーきー', enName: 'Shorkie', aliases: ['シーキー'], jkcGroup: '', akcGroup: 'Mixed', sizeDefault: 'SS', coatLength: '長毛', coatType: 'シングル', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 4, coldRisk: 3, humidityRisk: 4, respiratoryRisk: 4, eyeRisk: 4, shortNose: true), notesJa: 'シーズー×ヨークシャー。短頭傾向あり。'),
  Breed(id: 'morkie', jaName: 'モーキー', kana: 'もーきー', enName: 'Morkie', aliases: ['モルキー'], jkcGroup: '', akcGroup: 'Mixed', sizeDefault: 'SS', coatLength: '長毛', coatType: 'シングル', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 3, coldRisk: 3, humidityRisk: 3, earRisk: 3, eyeRisk: 3), notesJa: 'マルチーズ×ヨークシャー。小型で愛らしい。'),
  Breed(id: 'maltipoo', jaName: 'マルチプー', kana: 'まるちぷー', enName: 'Maltipoo', aliases: ['マルティプー'], jkcGroup: '', akcGroup: 'Mixed', sizeDefault: 'S', coatLength: '長毛', coatType: '巻き毛', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 3, coldRisk: 3, humidityRisk: 3, earRisk: 3), notesJa: 'マルチーズ×プードル。被毛管理が必要。'),
  Breed(id: 'labradoodle', jaName: 'ラブラドゥードル', kana: 'らぶらどぅーどる', enName: 'Labradoodle', aliases: ['ラブラドードル'], jkcGroup: '', akcGroup: 'Mixed', sizeDefault: 'L', coatLength: '中毛', coatType: '巻き毛', exerciseLevel: 'high', risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3, jointRisk: 3, earRisk: 3), notesJa: 'ラブラドール×プードル。大型で活発。'),
  Breed(id: 'bernedoodle', jaName: 'バーネドゥードル', kana: 'ばーねどぅーどる', enName: 'Bernedoodle', aliases: ['バーニードゥードル'], jkcGroup: '', akcGroup: 'Mixed', sizeDefault: 'XL', coatLength: '中毛', coatType: '巻き毛', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 4, coldRisk: 2, humidityRisk: 3, jointRisk: 4, earRisk: 3, giantBreed: true), notesJa: 'バーニーズ×プードル。大型で暑さに弱い。'),
  Breed(id: 'cavapoo', jaName: 'キャバプー', kana: 'きゃばぷー', enName: 'Cavapoo', aliases: ['キャバプー'], jkcGroup: '', akcGroup: 'Mixed', sizeDefault: 'S', coatLength: '中毛', coatType: '巻き毛', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 3, coldRisk: 3, humidityRisk: 3, respiratoryRisk: 3, earRisk: 4), notesJa: 'キャバリア×プードル。心臓疾患リスクに注意。'),
  Breed(id: 'english_bulldog', jaName: 'イングリッシュ・ブルドッグ', kana: 'いんぐりっしゅぶるどっぐ', enName: 'English Bulldog', aliases: ['ブルドッグ'], jkcGroup: '2', akcGroup: 'Non-Sporting', sizeDefault: 'M', coatLength: '短毛', coatType: 'シングル', exerciseLevel: 'low', risk: BreedRisk(heatRisk: 5, coldRisk: 3, humidityRisk: 5, respiratoryRisk: 5, skinRisk: 4, jointRisk: 4, eyeRisk: 4, shortNose: true), notesJa: '短頭種の代表。夏の散歩は非常に危険。'),
  Breed(id: 'boston_terrier', jaName: 'ボストン・テリア', kana: 'ぼすとんてりあ', enName: 'Boston Terrier', aliases: ['ボストンテリア'], jkcGroup: '9', akcGroup: 'Non-Sporting', sizeDefault: 'S', coatLength: '短毛', coatType: 'シングル', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 4, coldRisk: 3, humidityRisk: 4, respiratoryRisk: 4, eyeRisk: 4, shortNose: true), notesJa: '短頭種。目が大きく傷つきやすい。'),
  Breed(id: 'dalmatian', jaName: 'ダルメシアン', kana: 'だるめしあん', enName: 'Dalmatian', aliases: ['ダルマチアン'], jkcGroup: '6', akcGroup: 'Non-Sporting', sizeDefault: 'L', coatLength: '短毛', coatType: 'シングル', exerciseLevel: 'very_high', risk: BreedRisk(heatRisk: 3, coldRisk: 3, humidityRisk: 3, jointRisk: 3, stomachRisk: 3), notesJa: '非常に活発。尿路結石リスクあり。'),
  Breed(id: 'miniature_pinscher', jaName: 'ミニチュア・ピンシャー', kana: 'みにちゅあぴんしゃー', enName: 'Miniature Pinscher', aliases: ['ミニピン'], jkcGroup: '2', akcGroup: 'Toy', sizeDefault: 'S', coatLength: '短毛', coatType: 'シングル', exerciseLevel: 'high', risk: BreedRisk(heatRisk: 3, coldRisk: 4, humidityRisk: 3, jointRisk: 3), notesJa: '小型だが活発。寒さに弱く冬は防寒が必要。'),
  Breed(id: 'italian_greyhound', jaName: 'イタリアン・グレーハウンド', kana: 'いたりあんぐれーはうんど', enName: 'Italian Greyhound', aliases: ['イタグレ'], jkcGroup: '10', akcGroup: 'Toy', sizeDefault: 'S', coatLength: '短毛', coatType: 'シングル', exerciseLevel: 'high', risk: BreedRisk(heatRisk: 3, coldRisk: 5, humidityRisk: 2, jointRisk: 4, skinRisk: 3), notesJa: '体脂肪が少なく極端に寒さに弱い。骨折リスクも高い。'),
  Breed(id: 'welsh_corgi_cardigan', jaName: 'ウェルシュ・コーギー・カーディガン', kana: 'うぇるしゅこーぎーかーでぃがん', enName: 'Welsh Corgi Cardigan', aliases: ['カーディガン'], jkcGroup: '1', akcGroup: 'Herding', sizeDefault: 'M', coatLength: '中毛', coatType: 'ダブル', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3, jointRisk: 3, longBack: true), notesJa: '胴長で椎間板ヘルニアリスクあり。'),
  Breed(id: 'newfoundland', jaName: 'ニューファンドランド', kana: 'にゅーふぁんどらんど', enName: 'Newfoundland', aliases: ['ニューファン'], jkcGroup: '2', akcGroup: 'Working', sizeDefault: 'XL', coatLength: '長毛', coatType: 'ダブル', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 4, coldRisk: 1, humidityRisk: 4, jointRisk: 4, stomachRisk: 4, giantBreed: true), notesJa: '超大型犬。夏の熱中症に特に注意。'),
  Breed(id: 'great_pyrenees', jaName: 'グレート・ピレニーズ', kana: 'ぐれーとぴれにーず', enName: 'Great Pyrenees', aliases: ['ピレニーズ', 'ピレネー犬'], jkcGroup: '2', akcGroup: 'Working', sizeDefault: 'XL', coatLength: '長毛', coatType: 'ダブル', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 4, coldRisk: 1, humidityRisk: 3, jointRisk: 4, giantBreed: true), notesJa: '白い長毛の超大型犬。夏の熱中症に要注意。'),
  Breed(id: 'hokkaido_dog', jaName: '北海道犬', kana: 'ほっかいどうけん', enName: 'Hokkaido Dog', aliases: ['北海道'], jkcGroup: '5', akcGroup: 'Foundation Stock', sizeDefault: 'M', coatLength: '短毛', coatType: 'ダブル', exerciseLevel: 'high', risk: BreedRisk(heatRisk: 3, coldRisk: 1, humidityRisk: 2), notesJa: '寒さに非常に強い日本犬。夏場は注意が必要。'),
  Breed(id: 'kishu_dog', jaName: '紀州犬', kana: 'きしゅうけん', enName: 'Kishu Ken', aliases: ['紀州'], jkcGroup: '5', akcGroup: 'Foundation Stock', sizeDefault: 'M', coatLength: '短毛', coatType: 'ダブル', exerciseLevel: 'high', risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3), notesJa: '日本犬。丈夫だが運動量が多い。'),
  Breed(id: 'kai_dog', jaName: '甲斐犬', kana: 'かいけん', enName: 'Kai Ken', aliases: ['甲斐'], jkcGroup: '5', akcGroup: 'Foundation Stock', sizeDefault: 'M', coatLength: '短毛', coatType: 'ダブル', exerciseLevel: 'high', risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 2), notesJa: '虎毛が特徴の日本犬。活発で体力がある。'),
  Breed(id: 'shikoku_dog', jaName: '四国犬', kana: 'しこくけん', enName: 'Shikoku Ken', aliases: ['四国'], jkcGroup: '5', akcGroup: 'Foundation Stock', sizeDefault: 'M', coatLength: '短毛', coatType: 'ダブル', exerciseLevel: 'high', risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 2), notesJa: '日本犬の中でもワイルドな性格。運動量が多い。'),
  Breed(id: 'tosa_dog', jaName: '土佐犬', kana: 'とさけん', enName: 'Tosa Ken', aliases: ['土佐'], jkcGroup: '2', akcGroup: 'Working', sizeDefault: 'XL', coatLength: '短毛', coatType: 'シングル', exerciseLevel: 'medium', risk: BreedRisk(heatRisk: 3, coldRisk: 2, humidityRisk: 3, jointRisk: 4, stomachRisk: 4, giantBreed: true), notesJa: '超大型犬。関節と胃拡張に注意が必要。'),
];

// =============================
// 全犬種リスト
// =============================
const List<Breed> allBreeds = [
  ...jkc1gBreeds,
  ...jkc2gBreeds,
  ...jkc3gBreeds,
  ...jkc4gBreeds,
  ...jkc5gBreeds,
  ...jkc6gBreeds,
  ...jkc7gBreeds,
  ...jkc8gBreeds,
  ...jkc9gBreeds,
  ...jkc10gBreeds,
  ...akcOnlyBreeds,
];

// =============================
// 検索関数
// =============================
List<Breed> searchBreeds(String query) {
  if (query.isEmpty) return allBreeds;
  final q = query.toLowerCase();
  return allBreeds.where((b) {
    return b.jaName.contains(query) ||
        b.kana.contains(q) ||
        b.enName.toLowerCase().contains(q) ||
        b.aliases.any((a) => a.toLowerCase().contains(q));
  }).toList();
}

// =============================
// ミックス犬リスク合成
// =============================
BreedRisk mixBreedRisk(Breed b1, Breed b2, double weight1) {
  final w2 = 1.0 - weight1;
  int blend(int v1, int v2) => (v1 * weight1 + v2 * w2).round();
  int safe(int v1, int v2) => v1 > v2 ? v1 : v2; // 安全系はmax

  return BreedRisk(
    heatRisk: safe(b1.risk.heatRisk, b2.risk.heatRisk),
    coldRisk: blend(b1.risk.coldRisk, b2.risk.coldRisk),
    humidityRisk: safe(b1.risk.humidityRisk, b2.risk.humidityRisk),
    respiratoryRisk: safe(b1.risk.respiratoryRisk, b2.risk.respiratoryRisk),
    skinRisk: blend(b1.risk.skinRisk, b2.risk.skinRisk),
    jointRisk: safe(b1.risk.jointRisk, b2.risk.jointRisk),
    earRisk: blend(b1.risk.earRisk, b2.risk.earRisk),
    eyeRisk: blend(b1.risk.eyeRisk, b2.risk.eyeRisk),
    stomachRisk: safe(b1.risk.stomachRisk, b2.risk.stomachRisk),
    shortNose: b1.risk.shortNose || b2.risk.shortNose,
    longBack: b1.risk.longBack || b2.risk.longBack,
    giantBreed: b1.risk.giantBreed || b2.risk.giantBreed,
  );
}
